### ISSUE TITLE
Excessive warnings: Serialized project referenced reflection

### ISSUE THREAD

**Issue by am29d** [Gerrit0/typedoc-plugin-zod#6] opened 2024-08-13 20:04 UTC
H @Gerrit0 ,

thanks for creating the plugin. We have been using it in our project for a while now and it's super helpful to trim the long and nested schemas. 

We have been cleaning up the api doc warnings recently and [noticed a huge list of warnings](https://github.com/aws-powertools/powertools-lambda-typescript/issues/2923) coming from `typedoc-plugin-zod`

> [warning] Serialized project referenced reflection 6859, which was not a part of the project

It starts with 927, so it's a bit of a pain to scroll back and forth across thousands of lines to see the other warnings. It'd be helpful to understand what's causing the error on our side, and if there is chance we can fix it. 

## Steps to reporoduce

1. git clone git@github.com:aws-powertools/powertools-lambda-typescript.git
2. npm i
3. npm run docs-generateApiDoc

## Versions

- node 20.10.0
- typedoc 0.26.5
- typedoc-plugin-zod 1.2.0

Best,
Alex

**Comment by Gerrit0** [comment] 2024-08-14 01:21
This is *probably* caused by this plugin overwriting object types... it in theory should be reproducible with one of the test cases I already have in this repo with packages mode....

The fix is rather annoying, and something I'd *like* to solve in typedoc itself at some point.

**Comment by am29d** [comment] 2024-08-14 07:01
Thanks for swift response, appreciate it. So I assume we can't do anything on our side and need to wait for the typedoc fix. 

Should I open in the typedoc repo?

**Comment by Gerrit0** [comment] 2024-08-15 01:00
In theory it can be fixed by this plugin, I'd prefer to have a way to tell TypeDoc to do the necessary reflection removal surgery rather than implementing it here + in other plugins... This issue is fine for tracking

**Closed as completed** 2024-08-18 17:37 UTC

**Comment by Gerrit0** [comment] 2024-08-18 17:39
Well, it turns out.... it can be *mostly* fixed by this plugin. It also needs a fix upstream.
